apiVersion: v1
kind: Service
metadata:
  name: mocapweb-service
  labels:
    app: mocapweb-service
spec:
  type: NodePort
  selector:
    app: mocapwebapp
  ports:
  - protocol: TCP
    nodePort: 30000
    port: 80
    targetPort: 80